DELETE FROM country;

INSERT INTO country (co_code, co_name) VALUES ('AF', 'Afghanistan');
INSERT INTO country (co_code, co_name) VALUES ('AL', 'Albania');
INSERT INTO country (co_code, co_name) VALUES ('DZ', 'Algeria');
INSERT INTO country (co_code, co_name) VALUES ('AR', 'Argentina');
INSERT INTO country (co_code, co_name) VALUES ('AU', 'Australia');
INSERT INTO country (co_code, co_name) VALUES ('AT', 'Austria');
INSERT INTO country (co_code, co_name) VALUES ('BE', 'Belgium');
INSERT INTO country (co_code, co_name) VALUES ('BR', 'Brazil');
INSERT INTO country (co_code, co_name) VALUES ('CA', 'Canada');
INSERT INTO country (co_code, co_name) VALUES ('CN', 'China');
INSERT INTO country (co_code, co_name) VALUES ('CO', 'Colombia');
INSERT INTO country (co_code, co_name) VALUES ('DK', 'Denmark');
INSERT INTO country (co_code, co_name) VALUES ('EG', 'Egypt');
INSERT INTO country (co_code, co_name) VALUES ('FI', 'Finland');
INSERT INTO country (co_code, co_name) VALUES ('FR', 'France');
INSERT INTO country (co_code, co_name) VALUES ('DE', 'Germany');
INSERT INTO country (co_code, co_name) VALUES ('GR', 'Greece');
INSERT INTO country (co_code, co_name) VALUES ('IN', 'India');
INSERT INTO country (co_code, co_name) VALUES ('ID', 'Indonesia');
INSERT INTO country (co_code, co_name) VALUES ('IR', 'Iran');
INSERT INTO country (co_code, co_name) VALUES ('IQ', 'Iraq');
INSERT INTO country (co_code, co_name) VALUES ('IE', 'Ireland');
INSERT INTO country (co_code, co_name) VALUES ('IL', 'Israel');
INSERT INTO country (co_code, co_name) VALUES ('IT', 'Italy');
INSERT INTO country (co_code, co_name) VALUES ('JP', 'Japan');
INSERT INTO country (co_code, co_name) VALUES ('MX', 'Mexico');
INSERT INTO country (co_code, co_name) VALUES ('NL', 'Netherlands');
INSERT INTO country (co_code, co_name) VALUES ('NZ', 'New Zealand');
INSERT INTO country (co_code, co_name) VALUES ('NG', 'Nigeria');
INSERT INTO country (co_code, co_name) VALUES ('NO', 'Norway');
INSERT INTO country (co_code, co_name) VALUES ('PK', 'Pakistan');
INSERT INTO country (co_code, co_name) VALUES ('PE', 'Peru');
INSERT INTO country (co_code, co_name) VALUES ('PH', 'Philippines');
INSERT INTO country (co_code, co_name) VALUES ('PL', 'Poland');
INSERT INTO country (co_code, co_name) VALUES ('PT', 'Portugal');
INSERT INTO country (co_code, co_name) VALUES ('RU', 'Russia');
INSERT INTO country (co_code, co_name) VALUES ('SA', 'Saudi Arabia');
INSERT INTO country (co_code, co_name) VALUES ('ZA', 'South Africa');
INSERT INTO country (co_code, co_name) VALUES ('ES', 'Spain');
INSERT INTO country (co_code, co_name) VALUES ('SE', 'Sweden');
INSERT INTO country (co_code, co_name) VALUES ('CH', 'Switzerland');
INSERT INTO country (co_code, co_name) VALUES ('TH', 'Thailand');
INSERT INTO country (co_code, co_name) VALUES ('TR', 'Turkey');
INSERT INTO country (co_code, co_name) VALUES ('UA', 'Ukraine');
INSERT INTO country (co_code, co_name) VALUES ('GB', 'United Kingdom');
INSERT INTO country (co_code, co_name) VALUES ('US', 'United States');
INSERT INTO country (co_code, co_name) VALUES ('VN', 'Vietnam');
